### ISSUE TITLE
Blank start page

### ISSUE THREAD

**Issue by karanja-simon** [TID-Lab/aggie#201]
I setup Aggie as per the instruction, but after running http://localhost:3000, am getting a blank page with aggie version at the bottom. On closer inspection, there is a file app.min.js that the browser is trying to load but it's not available in js/app.min.js. What could be the issue.
See the sceenshot below
![screenshot from 2016-10-12 04-38-54](https://cloud.githubusercontent.com/assets/8024971/19308695/d61f3d38-9035-11e6-894b-5518ad40b19e.png)

**Comment by andresfib** [comment]
Thanks for reporting this. app.min.js should have been creating during normal installation. If not, running `gulp angular` should create it. We will try to reproduce your problem, and fix it for next releases.

**Comment by karanja-simon** [comment]
Thank you for your prompt feedback. It works flawlessly now.

**Comment by andresfib** [comment]
No problem! 
It would be good to know why it was not created. What happened when you run `npm install`? Could you attach the console output?

**Comment by karanja-simon** [comment]
Sorry, I have already cleared the console, but I am planning the setup the system on the another machine. I will report with the console output should the problem arises again.

**Comment by karanja-simon** [comment]
Sorry, I have already cleared the console, but I am planning to setup the system on the another machine. I will report with the console output should the problem arises again.

**Comment by mrphs** [comment]
I think I just ran into the same issue trying to install an instance of aggie. `npm install` returns the following:

```
$ npm install

> aggie@3.0.0 postinstall /home/ubuntu/aggie
> gulp build

[21:39:54] Using gulpfile ~/aggie/gulpfile.js
[21:39:54] Starting 'build'...
[21:39:54] Starting 'debugTranslations'...
[21:39:54] Starting 'angular'...
[21:39:54] Starting 'sass'...
[21:39:54] Finished 'sass' after 322 ms
[21:39:54] Finished 'debugTranslations' after 338 ms
[21:40:08] Finished 'angular' after 14 s
[21:40:08] Finished 'build' after 14 s
npm WARN karma-browserify@7.0.0 requires a peer of watchify@>=3 <4 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/gulp-mocha/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/karma/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/mocha/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/pm2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/sass/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 1538 packages in 22.637s

63 packages are looking for funding
  run `npm fund` for details

found 125 vulnerabilities (14 low, 32 moderate, 60 high, 19 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

this is what I get when I run `npm audit fix`:
```

$ npm audit fix
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/pm2/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/pm2/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN karma-browserify@7.0.0 requires a peer of watchify@>=3 <4 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/sass/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/mocha/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/karma/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/gulp-mocha/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ nconf@0.12.0
+ async@3.2.4
+ pm2@5.2.0
+ winston@3.8.2
+ ejs@3.1.8
+ moment@2.29.4
+ passport@0.6.0
added 70 packages from 47 contributors, removed 30 packages, updated 115 packages and moved 1 package in 19.941s

68 packages are looking for funding
  run `npm fund` for details

fixed 44 of 125 vulnerabilities in 1538 scanned packages
  23 vulnerabilities required manual review and could not be updated
  7 package updates for 58 vulnerabilities involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)
```

And this is what I get when I run `gulp angular` as suggested above:

```
~/aggie$ gulp angular
internal/util.js:209
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at promisify (internal/util.js:209:11)
    at Object.<anonymous> (/home/ubuntu/aggie/node_modules/get-stream/index.js:7:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ubuntu/aggie/node_modules/execa/lib/stream.js:3:19)
```

I don't have much knowledge about node, so I would appreciate it if anyone could point out what I'm doing wrong here.

**Comment by mrphs** [comment]
hmm interesting enough, when I got frustrated and started fresh on a new ec2 machine the problem did not occur.
