### ISSUE TITLE
NPM START 

### ISSUE THREAD

**Issue by salissadiq** [TID-Lab/aggie#278]
Error: The module '/Users/salscodes/Desktop/aggie/node_modules/mongodb/node_modules/bson/build/Release/bson.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 44. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:682:18)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/salscodes/Desktop/aggie/node_modules/mongodb/node_modules/bson/ext/index.js:15:10)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
js-bson: Failed to load c++ bson extension, using pure JS version
/Users/salscodes/Desktop/aggie/lib/database.js:4
var config = require('../config/secrets').get();
                                          ^

TypeError: require(...).get is not a function
    at Object.<anonymous> (/Users/salscodes/Desktop/aggie/lib/database.js:4:43)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/salscodes/Desktop/aggie/install.js:3:16)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aggie@2.6.0 prestart: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aggie@2.6.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/salscodes/.npm/_logs/2018-09-25T14_16_05_705Z-debug.log

**Comment by TheDanieLNK** [comment]
Closing this since it's been a while. Let me know if you still need help with starting Aggie.
