### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by psegovias** [TID-Lab/aggie#86]
module.js:485
    throw err;
          ^
SyntaxError: /var/www/aggie/config/secrets.json: Unexpected token v
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:482:27)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/aggie/lib/database.js:2:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

What i miss?

**Comment by davidenq** [comment]
I had the same mistake because I was writing comments on the json file. But with the  comment of vkareh, I solved this problem. Sorry for my english I'm begginer :).
Thanks.
